### ISSUE TITLE
As a user, I want a tailored ATO checklist

### ISSUE THREAD

**Issue by DavidEBest** [18F/compliance-toolkit#17]
- [ ] Visibility of the tasks across the project team and beyond (maybe public?)
- [ ] Nice-to-have: the ability to assign different tasks to different people
- [ ] There's an ability to have a discussion around individual tasks (and maybe the overall process?)
- [ ] Tasks added/removed based on responses to questions
- [ ] Nice-to-have: Ability to attach a link to the completed thing
- [ ] Sign-off on this plan from 18F's designated Authorizing Official

**Comment by afeld** [comment]
Current checklist: https://pages.18f.gov/before-you-ship/ato/checklist/
